services:
  app:
    image: ${UNIFI_IMAGE:-linuxserver/unifi-network-application}:${UNIFI_VERSION:?}
    container_name: ${UNIFI_NAME:-unifi}
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE:-America/New_York}
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DBNAME: ${MONGO_DBNAME:-unifi}
      MONGO_USER: ${MONGO_USER:-unifi}
      MONGO_PASS: ${MONGO_PASS:?}
    volumes:
      - app:/config
    ports:
      - ${ENDPOINT:-8443}:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080

  db:
    image: ${MONGO_IMAGE:-mongo}:${MONGO_VERSION:?}
    container_name: ${MONGO_NAME:-unifi-db}
    volumes:
      - db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  db:
  app:
